### ISSUE TITLE
How can I run this without live recognization?

### ISSUE THREAD

**Issue by SaiSandeepKantareddy** [ck090/FaceRecognition_DeepNeuralNetworks#2]

**Comment by ck090** [comment]
From line 88 in the dlibopen.py code.
If you go through the logic of the code, i'm processing individual frames of a video, instead of that just pass an image to that function !
Just a little change in the code will make that change!

**Comment by SaiSandeepKantareddy** [comment]
I also need to comment some of the lines right?
If you could do that and separately keeping files may useful to all.
Hope u do that.

**Comment by ck090** [comment]
Hey it's quite an easy task to do that go through the logic after line 88 and change/comment some stuff .. I'm quite busy now. I'll probably update this repo in a month or so. 
I'll update this issue and then close it
Is it fine

**Comment by SaiSandeepKantareddy** [comment]
yes cool. Got it.

**Comment by SaiSandeepKantareddy** [comment]
For comparing images(encodings) how about using KNN algorithm, did u tried that?

**Comment by ck090** [comment]
No man. I have done it for live feed recognition. I used deep learning method which has a CNN with hundreds of layers. I think you can do it that way as well! More over try changing this code for only images. 
Fork this repo and try it out
